# Generated by Django 6.0.8 on 2026-08-30 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CleanupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("api", "API"),
                            ("auto", "Auto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("dry_run", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("files_scanned", models.PositiveIntegerField(default=0)),
                ("files_deleted", models.PositiveIntegerField(default=0)),
                ("files_failed", models.PositiveIntegerField(default=0)),
                ("bytes_freed", models.PositiveBigIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleanup_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CleanupRunFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file_path", models.CharField(max_length=1024)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("deleted", models.BooleanField(default=False)),
                ("quarantined", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="cleanup_app.cleanuprun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="cleanuprun",
            index=models.Index(
                fields=["status", "-started_at"], name="cleanup_app_status_18ba50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cleanuprun",
            index=models.Index(fields=["trigger"], name="cleanup_app_trigger_915e97_idx"),
        ),
        migrations.AddIndex(
            model_name="cleanuprunfile",
            index=models.Index(fields=["run", "deleted"], name="cleanup_app_run_id_4f1e2a_idx"),
        ),
    ]
