# Generated by Django 6.0.8 on 2026-08-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cleanup_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrphanFile",
            fields=[
                (
                    "file_path",
                    models.CharField(
                        max_length=1024, primary_key=True, serialize=False, verbose_name="file path"
                    ),
                ),
                ("file_size", models.PositiveBigIntegerField(verbose_name="file size")),
            ],
            options={
                "verbose_name": "orphaned file",
                "verbose_name_plural": "orphaned files",
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
