/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cleanup/admin/orphans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orphaned files
         * @description Paginated list of files found on the configured storage that no installed model currently references, served from the cached OrphanScanner snapshot — a cache miss triggers exactly one scan, a hit never re-scans storage.
         */
        get: operations["orphans_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cleanup/admin/orphans/delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete orphaned files
         * @description Deletes the given files, each of which must be present in the current orphan snapshot. Rejects (400) any path not found there — never accepts an arbitrary client-supplied path.
         */
        post: operations["orphans_delete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cleanup/admin/runs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cleanup runs
         * @description Paginated CleanupRun history, optionally filtered by status/trigger.
         */
        get: operations["runs_list"];
        put?: never;
        /**
         * Trigger a cleanup run
         * @description If CLEANUP['USE_CELERY'] is on and celery is importable: enqueues the run and returns 202 with a PENDING CleanupRun. Otherwise runs synchronously and returns 200 with the finished run.
         */
        post: operations["runs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cleanup/admin/runs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a cleanup run
         * @description A single CleanupRun plus its CleanupRunFile rows.
         */
        get: operations["runs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cleanup/admin/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cleanup history summary
         * @description Aggregate totals across every CleanupRun, cached short-lived.
         */
        get: operations["summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Read-only — every field on ``CleanupRun`` is server-computed; nothing here is ever
         *     client-writable directly (``POST /runs/`` goes through ``CleanupTriggerRequestSerializer``
         *     instead).
         */
        CleanupRun: {
            readonly id: number;
            readonly status: components["schemas"]["StatusEnum"];
            readonly trigger: components["schemas"]["TriggerEnum"];
            readonly dry_run: boolean;
            readonly initiated_by: number;
            /** Format: date-time */
            readonly started_at: string;
            /** Format: date-time */
            readonly finished_at: string | null;
            readonly files_scanned: number;
            readonly files_deleted: number;
            readonly files_failed: number;
            readonly bytes_freed: number;
            readonly error: string;
        };
        /** @description ``GET /runs/{id}/`` — the list serializer plus its ``CleanupRunFile`` rows. */
        CleanupRunDetail: {
            readonly id: number;
            readonly status: components["schemas"]["StatusEnum"];
            readonly trigger: components["schemas"]["TriggerEnum"];
            readonly dry_run: boolean;
            readonly initiated_by: number;
            /** Format: date-time */
            readonly started_at: string;
            /** Format: date-time */
            readonly finished_at: string | null;
            readonly files_scanned: number;
            readonly files_deleted: number;
            readonly files_failed: number;
            readonly bytes_freed: number;
            readonly error: string;
            readonly files: components["schemas"]["CleanupRunFile"][];
        };
        CleanupRunFile: {
            readonly id: number;
            readonly file_path: string;
            readonly file_size: number;
            readonly deleted: boolean;
            readonly quarantined: boolean;
            readonly error: string;
        };
        /**
         * @description Response shape for ``GET /summary/`` — used only for ``@extend_schema``'s declared
         *     response type; the view builds this dict itself rather than instantiating this serializer
         *     against a model instance.
         */
        CleanupSummary: {
            readonly total_runs: number;
            readonly files_deleted_total: number;
            readonly bytes_freed_total: number;
            /** Format: date-time */
            readonly last_run_at: string | null;
            readonly last_run_status: string | null;
        };
        /** @description ``POST /runs/``'s request body — the only client-writable field for a triggered run. */
        CleanupTriggerRequestRequest: {
            /** @default false */
            dry_run: boolean;
        };
        /**
         * @description Validates ``POST /orphans/delete/``'s ``{"file_paths": [...]}`` body against the
         *     *current* cached ``OrphanScanner`` snapshot — the rail that keeps an arbitrary client-supplied
         *     path from ever reaching ``CleanupService`` (``docs/CONTRACT.md`` §4: "never accepts an
         *     arbitrary client-supplied path").
         */
        OrphanDeleteRequestRequest: {
            file_paths: string[];
        };
        /**
         * @description Serializes ``services.OrphanFileInfo`` — a frozen dataclass, not a model — for
         *     ``GET /orphans/``. ``docs/CONTRACT.md`` §4's frozen item shape: ``{file_path, file_size,
         *     modified_at}``, no ``file_url`` (``file_path`` is already storage-relative, never absolute —
         *     ``services._walk`` never yields anything else — so there is no ``MEDIA_ROOT`` leak to guard
         *     against).
         */
        OrphanFile: {
            readonly file_path: string;
            readonly file_size: number;
            /** Format: date-time */
            readonly modified_at: string;
        };
        PaginatedCleanupRunList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CleanupRun"][];
        };
        PaginatedOrphanFileList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["OrphanFile"][];
            /** @example 123456 */
            total_size?: number;
            /** @example 42 */
            files_scanned?: number;
            /** @example false */
            truncated?: boolean;
        };
        /**
         * @description * `pending` - Pending
         *     * `running` - Running
         *     * `success` - Success
         *     * `failed` - Failed
         *     * `partial` - Partial
         * @enum {string}
         */
        StatusEnum: "pending" | "running" | "success" | "failed" | "partial";
        /**
         * @description * `manual` - Manual
         *     * `scheduled` - Scheduled
         *     * `api` - API
         *     * `auto` - Auto
         * @enum {string}
         */
        TriggerEnum: "manual" | "scheduled" | "api" | "auto";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    orphans_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOrphanFileList"];
                };
            };
        };
    };
    orphans_delete_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrphanDeleteRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OrphanDeleteRequestRequest"];
                "multipart/form-data": components["schemas"]["OrphanDeleteRequestRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupRun"];
                };
            };
        };
    };
    runs_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Filter by run status. */
                status?: "failed" | "partial" | "pending" | "running" | "success";
                /** @description Filter by run trigger. */
                trigger?: "api" | "auto" | "manual" | "scheduled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCleanupRunList"];
                };
            };
        };
    };
    runs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CleanupTriggerRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CleanupTriggerRequestRequest"];
                "multipart/form-data": components["schemas"]["CleanupTriggerRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupRun"];
                };
            };
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupRun"];
                };
            };
        };
    };
    runs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupRunDetail"];
                };
            };
        };
    };
    summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupSummary"];
                };
            };
        };
    };
}
